### ISSUE TITLE
How to use Vite ?

### ISSUE THREAD

**Issue by revskill10** [hviana/faster_react#2]
Thanks for great library.

In my project, i need to use vite with custom babel plugin.

Is it possible to build with this framework ?

**Comment by hviana** [comment]
Hello, thanks.
I recommend you update your project. Just copy the app folder and options.json to a new project, I made several updates.

As for Vite, what exactly do you want? The framework already has an integrated bundle (it uses esbuild). You just need to import the libraries you want, it does the rest.

**Comment by revskill10** [comment]
Hi @hviana , we need to use custom babel plugin .

**Comment by hviana** [comment]
It is not possible, sorry.
